google_sheet_id: "1m5D7YDDxjY_cyXwb3ZUrKF9GXbGLx6o29MaOEnYPEdI"
google_sheet_non_util_node: "non_util_nodes"
google_sheet_util_node: "util_nodes"
google_sheet_link: "links"
google_sheet_potentials: "potentials"
google_sheet_criterion: "criterions"